Issue 271 - reprise de la documentation
IGNF/validator pull request #273
Opened 2022-01-17 06:53 UTC by mborne

Aperçu ici : https://github.com/IGNF/validator/tree/issue_271#validator

@slafayIGN Il restera à ajouter d'autres exemples pour la commande document_validator et faire une documentation dédié pour les plugins CNIG et DGPR, mais je pense qu'on peut merger ces premiers changements.

2022-01-17 14:30 UTC, slafayIGN requested changes
Je propose aussi un changement du paragraphe en anglais du readme : 

> This program validates a dataset (a folder containing geodata files and other documents) according to a schema describing the folder structure and the feature catalog. It outputs a report containing validation errors and warnings, and normalized data ready for database integration.
> 
> It has been originaly developped for the [Géoportail de l'urbanisme](https://www.geoportail-urbanisme.gouv.fr) to check urban planning documents against [CNIG standards](https://www.geoportail-urbanisme.gouv.fr/standard/) in order to produce a nationwide database.

2022-01-17 14:30 UTC, slafayIGN commented on CONTRIBUTING.md
> +Note that CI is configured throw [GitHub Actions](https://github.com/IGNF/validator/actions/workflows/main.yml).
through ?

2022-01-17 14:30 UTC, slafayIGN commented on CONTRIBUTING.md
> +* Ensure that you are on the good branch and that all code is committed and push (`git status`)
on the right branch

2022-01-17 14:30 UTC, slafayIGN commented on README.md
> +Le schéma suivant illustre le [principe de fonctionnement du validateur de document](doc/principe.md) :
Ce n'est jamais appelé "validateur de document". Rester sur "validateur" simplement.

2022-01-17 14:30 UTC, slafayIGN commented on README.md
> +Le validateur se présente sous la forme d'un exécutable java (`validator-cli.jar`) utilisable en ligne de commande. Il n'offre pas d'interface graphique car il a vocation à être utilisé pour la mise
mise en œuvre (o, e dans l'o)

2022-01-17 14:30 UTC, slafayIGN commented on README.md
>  ![Working principle](doc/img/principe.jpg)
"Principe de fonctionnement" comme texte alternatif vu que le readme est en français

2022-01-17 14:30 UTC, slafayIGN commented on README.md
>  ## Dépendances
ça ne devrait pas faire partie du readme, c'est décrit dans doc/cli.md avec en plus les détails pour ogr2ogr dans un fichier à part (peut-être pas nécessaire ou alors à remplacer par un fichier qui englobe toutes les dépendances doc/prerequisites.md)

2022-01-17 14:30 UTC, slafayIGN commented on README.md
> +* [Projection supportées (JSON)](validator-core/src/main/resources/projection.json)
Projections*

2022-01-17 14:30 UTC, slafayIGN commented on doc/cli.md
> +## Pré-requis
soit tout mettre dans un fichier prerequisites, soit ramener les explications ogr2ogr ici.

2022-01-17 18:53 UTC, mborne commented on doc/cli/document_validator.md
> +Ces conversions sont réalisées à l'aide de [ogr2ogr de GDAL](../dependencies/ogr2ogr.md). L'utilisation d'extension dédiées facilite principalement une nouvelle exécution du validateur sur un dossier
Vu, mais je pense qu'on sera potentiellement amené à détailler les commandes appelées

2022-01-17 18:53 UTC, mborne commented on doc/dependencies/geotools.md
> +# GeoTools
Vu, mais si ça te va, je conserve en l'état pour l'instant.

2022-01-17 18:56 UTC, mborne commented
@slafayIGN merci pour la relecture! j'ai pris en compte la plupart des suggestions

2022-01-20 13:44 UTC, slafayIGN approved these changes

2022-01-20 14:13 UTC, cboucheIGN approved these changes
good job

2022-01-20 14:13 UTC, cboucheIGN commented on CONTRIBUTING.md
> +## Create releases
Nice, i like that section

2022-02-03 11:30 UTC, mborne commented
Je merge après avoir testé en local (j'ignore pourquoi le contrôle de formatage est en échec uniquement avec github actions, mais ce n'est pas lié à cette reprise de la documentation).

2022-02-03 11:31 UTC, merged