validator-plugin-cnig: add GeometyInDocumentValidator
IGNF/validator pull request #339
Opened 2023-11-06 16:11 UTC by cboucheIGN

Activated when a document emprise is pass to the command line

2023-11-06 16:14 UTC, cboucheIGN commented
ref #327

2023-11-07 11:11 UTC, slafayIGN requested changes
👍 

La nouvelle fonctionnalité mériterait des exemples dans les .md de documentation.

Optionnellement une contrainte pour vérifier que l'emprise fournie est bien une emprise (polygone ou multi-polygone) me semble un ajout utile. Il y a peut-être d'autres contraintes auxquelles je ne pense pas sur la validité de l'emprise.

2023-11-07 11:11 UTC, slafayIGN commented on validator-core/src/test/java/fr/ign/validator/command/options/DocumentEmpriseOptionTest.java
> +            "POINT(1 1)"
C'est bizarre de ne faire des tests qu'avec un WKT ou un JSON ponctuel alors que le paramètre demande une emprise. On attendrait plutôt POLYGON ou MULTIPOLYGON non ?

Il y a des tests plus poussés plus loin, mais rajouter une contrainte sur le WKT ou JSON pour vérifier que c'est une "emprise" me paraitrait une bonne chose.

2023-11-07 11:11 UTC, slafayIGN commented on validator-core/src/main/java/fr/ign/validator/command/options/DocumentEmpriseOption.java
> +                "Path to a geometry or a geometry. WKT or GeoJSON format are supported. Declared in the same CRS than data source"
C'est la seule documentation accessible. Il faut également modifier la documentation ici https://github.com/IGNF/validator/blob/master/doc/cli/document_validator.md et y ajouter des exemples avec ce paramètre

2023-11-08 14:12 UTC, cboucheIGN commented on validator-core/src/test/java/fr/ign/validator/command/options/DocumentEmpriseOptionTest.java
> +            "POINT(1 1)"
Merci;

Commité.

2023-11-08 14:12 UTC, cboucheIGN commented on validator-core/src/main/java/fr/ign/validator/command/options/DocumentEmpriseOption.java
> +                "Path to a geometry or a geometry. WKT or GeoJSON format are supported. Declared in the same CRS than data source"
Merci;

Commité.

2023-11-08 14:23 UTC, slafayIGN approved these changes
🚀

2023-11-08 17:10 UTC, merged